baseURL = 'https://dpiotrkowski.github.io/MES'
languageCode = 'pl-PL'
title = 'IPI'
theme = 'hugo-book'


# enableGitInfo = true
disableKinds = ['taxonomy', 'taxonomyTerm']
[params]
  BookTheme = 'light'
  BookToC = true
  BookLogo = 'logo.svg'
  BookSection = 'docs'
  BookRepo = 'https://github.com/dpiotrkowski/MES'
